version: '2'
services:
  rancher-db:
    image: mariadb:10.2
    container_name: rancher-db
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - rancher-db_data:/var/lib/mysql
      - ~/rancher-server-dev/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  rancher-server:
    image: rancher/server
    container_name: rancher-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - rancher-db
    links:
      - rancher-db:mysql
    command: --db-host rancher-db

  rancher-proxy:
    image: nginx:1.16.0
    container_name: rancher-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/rancher-server-dev/letsencrypt:/etc/letsencrypt
      - ~/rancher-server-dev/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - rancher-server

volumes:
  rancher-db_data:
